# Generated by Django 4.1.6 on 2023-03-30 11:54

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TransitLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=16, unique=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Bus"),
                            (2, "Minibus"),
                            (3, "Tram"),
                            (4, "Trolleybus"),
                        ]
                    ),
                ),
                ("terminal1", models.CharField(max_length=32)),
                ("terminal2", models.CharField(max_length=32)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "occurrence",
                    models.CharField(
                        choices=[
                            ("lv", "Monday - Friday"),
                            ("s", "Saturday"),
                            ("d", "Sunday"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "terminal1_schedule",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=5),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "terminal2_schedule",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=5),
                        default=list,
                        size=None,
                    ),
                ),
                ("schedule_start_date", models.DateField(blank=True, null=True)),
                (
                    "line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="transit_lines.transitline",
                    ),
                ),
            ],
            options={
                "unique_together": {("line", "occurrence")},
            },
        ),
    ]
