# Generated by Django 4.1.6 on 2023-04-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit_lines', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transitline',
            old_name='type',
            new_name='car_type',
        ),
        migrations.AddField(
            model_name='transitline',
            name='has_bike_rack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transitline',
            name='line_type',
            field=models.IntegerField(choices=[(1, 'Metropolitan'), (2, 'Urban')], default=2),
            preserve_default=False,
        ),
    ]
