# Generated by Django 4.1.6 on 2023-03-28 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0002_bot_webhook_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bot",
            old_name="is_external",
            new_name="is_active",
        ),
    ]
