# Generated by Django 4.1.6 on 2024-01-05 13:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0004_message"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-date"]},
        ),
    ]
