# Generated by Django 5.0.4 on 2024-09-08 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bots", "0006_alter_bot_last_name_alter_bot_webhook_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bot",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="bot",
            name="webhook_name",
        ),
    ]
