sonar.exclusions=tests/**
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.organization=pradan
sonar.projectKey=andreipradan_mainframe
sonar.projectName=mainframe
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
sonar.sources=.
sonar.tests=tests
