sonar.projectKey=andreipradan_mainframe
sonar.organization=pradan

sonar.coverage.exclusions=**/migrations/**,frontend/src/**/__tests__/**,frontend/src/**/*.test.js,frontend/src/**/__mocks__/**,frontend/src/**/setupTests.js
sonar.coverage.inclusions=src/mainframe/**,frontend/src/**
sonar.exclusions=tests/**,**/migrations/**
sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info
sonar.projectName=mainframe
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
sonar.sources=.
sonar.tests=tests
