sonar.projectKey=andreipradan_mainframe
sonar.organization=pradan
sonar.coverage.exclusions=**/migrations/**
sonar.coverage.inclusions=src/mainframe/**,frontend/src/**
sonar.exclusions=tests/**,**/migrations/**
sonar.projectName=mainframe
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.12
sonar.sources=.
sonar.tests=tests
