# Generated by Django 5.2.10 on 2026-03-30 17:52

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sources", "0003_source_is_default_source_unique_default_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=256)),
                (
                    "categories",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64),
                        default=list,
                        size=None,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("start_date", models.DateTimeField()),
                ("url", models.URLField(unique=True)),
                ("additional_data", models.JSONField(blank=True, default=dict)),
                ("city", models.CharField(blank=True, max_length=64)),
                ("description", models.TextField(blank=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("external_id", models.CharField(blank=True, max_length=100)),
                ("location_url", models.URLField(blank=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sources.source"
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
    ]
