# Generated by Django 6.0.1 on 2026-03-25 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sources", "0003_source_is_default_source_unique_default_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("location_slug", models.CharField(blank=True, max_length=255)),
                ("city_name", models.CharField(blank=True, max_length=255)),
                ("city_slug", models.CharField(blank=True, max_length=255)),
                (
                    "category_id",
                    models.IntegerField(
                        choices=[
                            (1, "Music"),
                            (2, "Sport"),
                            (3, "Film"),
                            (4, "Other"),
                            (5, "Theater"),
                            (6, "Online"),
                        ],
                        db_index=True,
                        default=4,
                    ),
                ),
                ("url", models.URLField(blank=True)),
                ("external_id", models.CharField(max_length=100)),
                ("additional_data", models.JSONField(blank=True, default=dict)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sources.source"
                    ),
                ),
            ],
            options={
                "ordering": ["start_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "external_id"),
                        name="unique_source_external_id",
                    )
                ],
            },
        ),
    ]
