# Generated by Django 6.0.1 on 2026-03-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[("eb", "EB"), ("other", "Other")], max_length=50
                    ),
                ),
                ("external_id", models.CharField(max_length=100)),
                ("additional_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-start_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "external_id"),
                        name="unique_source_external_id",
                    )
                ],
            },
        ),
    ]
