# Generated by Django 5.2.10 on 2026-03-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="event",
            name="unique_source_external_id",
        ),
        migrations.RemoveField(
            model_name="event",
            name="category_id",
        ),
        migrations.RemoveField(
            model_name="event",
            name="city_name",
        ),
        migrations.RemoveField(
            model_name="event",
            name="city_slug",
        ),
        migrations.RemoveField(
            model_name="event",
            name="location_slug",
        ),
        migrations.AddField(
            model_name="event",
            name="category",
            field=models.CharField(default="other", max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="city",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="event",
            name="location_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="external_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="event",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
