# Generated by Django 6.0.1 on 2026-03-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="event",
            name="unique_source_external_id",
        ),
        migrations.AddField(
            model_name="event",
            name="location_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="url",
            field=models.URLField(unique=True),
        ),
    ]
