# Generated by Django 6.0.1 on 2026-03-25 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_event_city_name_event_city_slug_event_location_slug_and_more"),
        ("sources", "0003_source_is_default_source_unique_default_source"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["start_date"]},
        ),
        migrations.AddField(
            model_name="event",
            name="category_id",
            field=models.IntegerField(
                choices=[
                    (1, "Music"),
                    (2, "Sport"),
                    (3, "Film"),
                    (4, "Other"),
                    (5, "Theater"),
                    (6, "Online"),
                ],
                db_index=True,
                default=4,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sources.source"
            ),
        ),
    ]
