# Generated by Django 5.2.10 on 2026-06-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_favoriteband"),
        ("sources", "0004_remove_source_unique_default_source_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favoriteband",
            name="user",
        ),
        migrations.AlterField(
            model_name="event",
            name="url",
            field=models.URLField(),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("location", "start_date", "url"), name="unique_location"
            ),
        ),
        migrations.DeleteModel(
            name="FavoriteBand",
        ),
    ]
