# Generated by Django 6.0.1 on 2026-03-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_source"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["start_date"]},
        ),
    ]
