
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
        files: \*.py$
        exclude: migrations/
    -   id: trailing-whitespace
        files: \*.py$
        exclude: migrations/
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        exclude: migrations/
-   repo: https://github.com/myint/autoflake
    rev: v2.0.2
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable', '--ignore-init-module-imports']
        exclude: ^migrations/
