[tool.isort]
src_paths = ["."]

[tool.pytest.ini_options]
addopts = """\
           --nomigrations \
           --reuse-db \
           --disable-socket \
           -v
"""
DJANGO_SETTINGS_MODULE = "core.settings"
python_files = ["test_*.py"]

[tool.ruff]
target-version = "py310"
# https://docs.astral.sh/ruff/rules/
lint.select = [
    "I",   # isort
    "E",   # pycodestyle
    "F",   # pyflakes
    "PL",  # pylint
    "C90", # mccabe
    "B",   # flake8-bugbear
    "S",   # flake8-bandit
    "DJ",  # flake8-django
    "SIM", # flake8-simplify
    "T10", # flake8-debugger
    "G",   # flake8-logging-format
    "C4",  # flake8-comprehensions
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "S101", # asserts allowed in tests
    "PLR2004", # magic value used in comparison
]
