# Generated by Django 4.1.6 on 2023-07-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='number_of_months',
            field=models.IntegerField(default=348),
        ),
    ]
