# Generated by Django 4.1.6 on 2023-10-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exchange", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exchangerate",
            name="value",
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
    ]
