# Generated by Django 5.0.4 on 2024-04-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0003_alter_device_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
