# Generated by Django 5.0.4 on 2024-08-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0004_alter_device_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="additional_data",
            field=models.JSONField(default=dict),
        ),
    ]
