# Generated by Django 5.0.4 on 2024-08-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0005_device_additional_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="alias",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
