# Generated by Django 5.0.4 on 2024-08-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0006_device_alias"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
