# Generated by Django 5.0.4 on 2024-10-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0007_alter_device_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="should_notify_presence",
            field=models.BooleanField(default=True),
        ),
    ]
