# Generated by Django 5.0.4 on 2025-01-09 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("devices", "0008_device_should_notify_presence"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="last_seen",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
