# Generated by Django 4.2.4 on 2023-08-31 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0017_auto_20230831_2348"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                default="Unidentified",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="finance.category",
            ),
        ),
    ]
