# Generated by Django 4.2.4 on 2023-09-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0018_transaction_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="confirmed_by",
            field=models.SmallIntegerField(
                choices=[(0, "Unconfirmed"), (1, "Human"), (2, "ML")], default=0
            ),
        ),
    ]
