# Generated by Django 4.1.6 on 2023-12-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0023_payment_additional_data"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField()),
                ("currency", models.CharField(max_length=3)),
                ("fx_rate", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "price_per_share",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("ticker", models.CharField(blank=True, max_length=5, null=True)),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "BUY - MARKET"),
                            (2, "CASH TOP-UP"),
                            (3, "CASH WITHDRAWAL"),
                            (4, "CUSTODY FEE"),
                            (5, "DIVIDEND"),
                            (6, "OTHER"),
                            (7, "SELL - MARKET"),
                            (8, "STOCK SPLIT"),
                        ],
                        default=6,
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
        migrations.AddConstraint(
            model_name="stocktransaction",
            constraint=models.UniqueConstraint(
                fields=("date", "currency", "fx_rate", "total_amount", "type"),
                name="finance_stocktransaction_date_currency_fx_rate_total_amount_type_uniq",
            ),
        ),
    ]
