# Generated by Django 4.1.6 on 2024-01-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0024_stocktransaction_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PnL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=7)),
                ("cost_basis", models.DecimalField(decimal_places=3, max_digits=6)),
                ("currency", models.CharField(max_length=3)),
                ("date_acquired", models.DateTimeField()),
                ("date_sold", models.DateTimeField()),
                ("pnl", models.DecimalField(decimal_places=3, max_digits=7)),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=11)),
                ("ticker", models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
