# Generated by Django 5.0.1 on 2024-02-18 11:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0027_alter_pnl_cost_basis_alter_pnl_pnl"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ("-date", "-created_at")},
        ),
    ]
