# Generated by Django 5.0.1 on 2024-03-17 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0028_alter_payment_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timetable",
            options={"ordering": ("-date", "-created_at")},
        ),
    ]
