# Generated by Django 5.0.4 on 2024-07-16 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0030_alter_pnl_ticker_alter_stocktransaction_ticker"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"ordering": ("-date", "-remaining")},
        ),
    ]
