# Generated by Django 5.0.4 on 2024-08-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0031_alter_payment_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[
                    ("Current", "Current"),
                    ("Deposit", "Deposit"),
                    ("Savings", "Savings"),
                ],
                default="Current",
                max_length=7,
            ),
        ),
    ]
