# Generated by Django 5.0.4 on 2024-11-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0032_alter_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="pnl",
            name="country",
            field=models.CharField(default="US", max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pnl",
            name="isin",
            field=models.CharField(default="default", max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pnl",
            name="security_name",
            field=models.CharField(default="default", max_length=50),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="pnl",
            constraint=models.UniqueConstraint(
                fields=("date_acquired", "date_sold", "ticker", "quantity", "currency"),
                name="finance_pnl_date_acquired_date_sold_ticker_quantity_currency_uniq",
            ),
        ),
    ]
