# Generated by Django 5.0.4 on 2024-12-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0033_pnl_country_pnl_isin_pnl_security_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CryptoTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("date", models.DateTimeField()),
                (
                    "fees",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=18, null=True
                    ),
                ),
                ("symbol", models.CharField(blank=True, max_length=10)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Buy"),
                            (2, "Sell"),
                            (3, "Send"),
                            (4, "Receive"),
                            (5, "Payment"),
                            (6, "Stake"),
                            (7, "Unstake"),
                            (8, "Learn reward"),
                            (9, "Staking reward"),
                        ],
                        default=2,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
        migrations.AddConstraint(
            model_name="cryptotransaction",
            constraint=models.UniqueConstraint(
                fields=("date", "quantity", "symbol", "type"),
                name="finance_cryptotransaction_date_quantity_symbol_type_uniq",
            ),
        ),
    ]
