# Generated by Django 5.0.4 on 2025-01-10 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0037_pension_contribution_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="date",
            field=models.DateField(),
        ),
    ]
