# Generated by Django 5.0.4 on 2025-01-10 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0038_alter_contribution_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contribution",
            name="unit_value",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=12, null=True
            ),
        ),
    ]
