# Generated by Django 5.0.4 on 2025-01-10 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0039_alter_contribution_unit_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pension",
            name="total_units",
        ),
    ]
