# Generated by Django 5.0.4 on 2025-01-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0040_remove_pension_total_units"),
    ]

    operations = [
        migrations.AddField(
            model_name="pension",
            name="total_units",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=13),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="unit_value",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="contribution",
            name="units",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
