# Generated by Django 5.0.4 on 2025-01-10 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0041_pension_total_units_alter_contribution_unit_value_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pension",
            options={"ordering": ("name",)},
        ),
    ]
