# Generated by Django 5.0.4 on 2025-01-10 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0042_alter_pension_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="pension",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
