# Generated by Django 5.0.4 on 2025-01-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0044_unitvalue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unitvalue",
            name="amount",
        ),
        migrations.AddField(
            model_name="unitvalue",
            name="value",
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
