# Generated by Django 5.0.4 on 2025-01-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0045_remove_unitvalue_amount_unitvalue_value"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unitvalue",
            options={"ordering": ("-date",)},
        ),
        migrations.AddConstraint(
            model_name="unitvalue",
            constraint=models.UniqueConstraint(
                fields=("date", "pension", "value"),
                name="finance_unitvalue_date_pension_value_uniq",
            ),
        ),
    ]
