# Generated by Django 5.0.4 on 2025-01-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0046_alter_unitvalue_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="unitvalue",
            name="finance_unitvalue_date_pension_value_uniq",
        ),
        migrations.AddConstraint(
            model_name="unitvalue",
            constraint=models.UniqueConstraint(
                fields=("date", "pension"), name="finance_unitvalue_date_pension_uniq"
            ),
        ),
    ]
