# Generated by Django 5.0.4 on 2025-01-12 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0047_remove_unitvalue_finance_unitvalue_date_pension_value_uniq_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contribution",
            name="unit_value",
        ),
    ]
