# Generated by Django 5.0.4 on 2025-01-12 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0048_remove_contribution_unit_value"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pension",
            name="url",
        ),
    ]
