# Generated by Django 5.0.4 on 2025-01-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0049_remove_pension_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pension",
            name="account_number",
            field=models.CharField(default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="pension",
            name="employer",
            field=models.CharField(default="", max_length=32),
        ),
    ]
