# Generated by Django 5.0.4 on 2025-02-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0050_alter_pension_account_number_alter_pension_employer"),
    ]

    operations = [
        migrations.CreateModel(
            name="BondTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("commission", models.DecimalField(decimal_places=2, max_digits=8)),
                ("date", models.DateTimeField()),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=15)),
                ("maturity", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=128)),
                ("pnl", models.DecimalField(decimal_places=2, max_digits=8)),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("tax", models.DecimalField(decimal_places=2, max_digits=8)),
                ("ticker", models.CharField(max_length=10)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("cump", "Buy"),
                            ("in", "Deposit"),
                            ("div", "Dividend"),
                            ("vanz", "Sell"),
                        ],
                        max_length=7,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
