# Generated by Django 5.0.4 on 2025-02-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0051_bondtransaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bondtransaction",
            name="commission",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="bondtransaction",
            name="pnl",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
