# Generated by Django 5.0.4 on 2025-02-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0052_alter_bondtransaction_commission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bondtransaction",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AlterField(
            model_name="bondtransaction",
            name="tax",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
