# Generated by Django 5.0.4 on 2025-02-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0053_alter_bondtransaction_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bondtransaction",
            name="maturity",
            field=models.DateField(blank=True, null=True),
        ),
    ]
