# Generated by Django 5.0.4 on 2025-02-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0054_alter_bondtransaction_maturity"),
    ]

    operations = [
        migrations.AddField(
            model_name="bondtransaction",
            name="net",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
    ]
