# Generated by Django 5.0.4 on 2025-02-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0055_bondtransaction_net"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bondtransaction",
            name="net",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
