# Generated by Django 5.0.4 on 2025-02-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0056_alter_bondtransaction_net"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bondtransaction",
            options={"ordering": ("-date",)},
        ),
    ]
