# Generated by Django 5.0.4 on 2025-02-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0057_alter_bondtransaction_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                ("currency", models.CharField(max_length=3)),
                ("date", models.DateField()),
                ("interest", models.DecimalField(decimal_places=2, max_digits=5)),
                ("maturity", models.DateField()),
                ("name", models.CharField(max_length=65)),
                ("alias", models.CharField(blank=True, max_length=128)),
                ("pnl", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("tax", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
            options={
                "ordering": ("-date",),
            },
        ),
    ]
