# Generated by Django 5.0.4 on 2025-02-07 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0004_alter_currency_name"),
        ("finance", "0059_rename_deposittransaction_deposit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="currency",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="exchange.currency"
            ),
        ),
    ]
