# Generated by Django 5.0.4 on 2025-02-07 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0004_alter_currency_name"),
        ("finance", "0060_alter_deposit_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="bondtransaction",
            name="currency",
            field=models.ForeignKey(
                default="RON",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="exchange.currency",
            ),
            preserve_default=False,
        ),
    ]
