# Generated by Django 5.0.4 on 2025-02-07 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exchange", "0004_alter_currency_name"),
        ("finance", "0061_bondtransaction_currency"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BondTransaction",
            new_name="Bond",
        ),
    ]
