# Generated by Django 5.0.4 on 2025-02-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0062_rename_bondtransaction_bond"),
    ]

    operations = [
        migrations.AddField(
            model_name="bond",
            name="interest",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
