# Generated by Django 5.1.7 on 2025-04-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0063_bond_interest"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deposit",
            name="alias",
        ),
    ]
