# Generated by Django 5.1.7 on 2025-04-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0064_remove_deposit_alias"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pnl",
            name="finance_pnl_date_acquired_date_sold_ticker_quantity_currency_uniq",
        ),
        migrations.AddConstraint(
            model_name="pnl",
            constraint=models.UniqueConstraint(
                fields=(
                    "currency",
                    "date_acquired",
                    "date_sold",
                    "isin",
                    "ticker",
                    "quantity",
                ),
                name="finance_pnl_date_acquired_date_sold_ticker_quantity_currency_uniq",
            ),
        ),
    ]
