# Generated by Django 5.1.7 on 2025-04-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0065_remove_pnl_finance_pnl_date_acquired_date_sold_ticker_quantity_currency_uniq_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pnl",
            name="finance_pnl_date_acquired_date_sold_ticker_quantity_currency_uniq",
        ),
        migrations.AddConstraint(
            model_name="pnl",
            constraint=models.UniqueConstraint(
                fields=(
                    "amount",
                    "cost_basis",
                    "currency",
                    "date_acquired",
                    "date_sold",
                    "quantity",
                    "ticker",
                ),
                name="finance_pnl_date_acquired_date_sold_ticker_quantity_currency_uniq",
            ),
        ),
    ]
