# Generated by Django 5.1.7 on 2025-06-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "finance",
            "0066_remove_pnl_finance_pnl_date_acquired_date_sold_ticker_quantity_currency_uniq_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="bond",
            name="type",
            field=models.CharField(
                choices=[
                    ("cump", "Buy"),
                    ("in", "Deposit"),
                    ("div", "Dividend"),
                    ("vanz", "Sell"),
                    ("out", "Withdrawal"),
                ],
                max_length=7,
            ),
        ),
    ]
