# Generated by Django 5.1.7 on 2025-09-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0068_bond_interest_dates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pension",
            name="total_units",
        ),
    ]
