# Generated by Django 5.0.4 on 2025-01-14 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_car_serviceentry_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceentry",
            name="car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="service_entries",
                to="expenses.car",
            ),
        ),
    ]
