# Generated by Django 5.0.4 on 2025-03-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_alter_serviceentry_car"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceentry",
            name="date",
            field=models.DateField(),
        ),
    ]
