# Generated by Django 4.1.6 on 2023-12-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("earthquakes", "0002_earthquake_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="earthquake",
            name="additional_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
