# Generated by Django 4.1.6 on 2024-01-04 17:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("earthquakes", "0003_earthquake_additional_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="earthquake",
            options={"ordering": ("-timestamp",)},
        ),
    ]
