# Generated by Django 5.0.4 on 2024-04-30 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "earthquakes",
            "0005_alter_earthquake_depth_alter_earthquake_latitude_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="earthquake",
            name="intensity",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
