# Generated by Django 5.0.4 on 2024-04-30 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("earthquakes", "0006_alter_earthquake_intensity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="earthquake",
            name="intensity",
            field=models.CharField(default="", max_length=16),
        ),
    ]
