# Generated by Django 5.0.4 on 2024-08-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("earthquakes", "0008_earthquake_earthquakes_timesta_9d98cf_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="earthquake",
            name="earthquakes_timesta_9d98cf_idx",
        ),
        migrations.AddIndex(
            model_name="earthquake",
            index=models.Index(
                fields=["source", "-timestamp"], name="source_timestamp_idx"
            ),
        ),
    ]
