# Generated by Django 5.0.4 on 2025-02-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "earthquakes",
            "0009_remove_earthquake_earthquakes_timesta_9d98cf_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="earthquake",
            name="is_local",
            field=models.BooleanField(default=False),
        ),
    ]
