# Generated by Django 5.2.10 on 2026-07-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("earthquakes", "0010_earthquake_is_local"),
    ]

    operations = [
        migrations.AlterField(
            model_name="earthquake",
            name="timestamp",
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name="earthquake",
            constraint=models.UniqueConstraint(
                fields=("latitude", "longitude", "source", "timestamp"),
                name="unique_source",
            ),
        ),
    ]
