# Generated by Django 4.1.6 on 2023-03-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("devices", "0002_device_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
