# Generated by Django 4.1.6 on 2023-08-03 15:26

import django.db.models.deletion
from django.db import migrations, models

import finance.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_code", models.IntegerField()),
                ("first_name", models.CharField(max_length=32)),
                ("last_name", models.CharField(max_length=32)),
                ("number", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Credit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("currency", models.CharField(max_length=3)),
                ("date", models.DateField()),
                ("number", models.IntegerField(unique=True)),
                ("number_of_months", models.IntegerField()),
                ("total", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Timetable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amortization_table",
                    models.JSONField(validators=[
                        finance.models.validate_amortization_table
                    ]),
                ),
                ("date", models.DateField()),
                ("ircc", models.DecimalField(decimal_places=2, max_digits=8)),
                ("margin", models.DecimalField(decimal_places=2,
                                               max_digits=8)),
                (
                    "credit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.credit"),
                ),
            ],
            options={
                "ordering": ("-date", ),
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                (
                    "interest",
                    models.DecimalField(decimal_places=2,
                                        default=0,
                                        max_digits=8),
                ),
                ("is_prepayment", models.BooleanField(default=False)),
                (
                    "principal",
                    models.DecimalField(decimal_places=2,
                                        default=0,
                                        max_digits=8),
                ),
                ("remaining",
                 models.DecimalField(decimal_places=2, max_digits=8)),
                ("reference", models.IntegerField(blank=True, null=True)),
                (
                    "saved",
                    models.DecimalField(decimal_places=2,
                                        default=0,
                                        max_digits=8),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2,
                                        default=0,
                                        max_digits=8),
                ),
                (
                    "credit",
                    models.ForeignKey(
                        default=finance.models.get_default_credit,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.credit",
                    ),
                ),
            ],
            options={
                "ordering": ("-date", ),
            },
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                fields=("credit", "date", "is_prepayment", "reference",
                        "total"),
                name="finance_payment_credit_date_is_prepayment_reference_total_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reference__isnull", True)),
                fields=("credit", "date", "is_prepayment", "total"),
                name="finance_payment_credit_date_is_prepayment_total_uniq",
            ),
        ),
    ]
