# Generated by Django 4.1.6 on 2023-08-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(default='current', max_length=24),
        ),
    ]
