# Generated by Django 4.1.6 on 2023-08-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0003_account_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="bank",
            field=models.CharField(max_length=32),
            preserve_default=False,
        ),
    ]
