# Generated by Django 4.1.6 on 2023-08-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Current', 'Current'), ('Savings', 'Savings')], default='Current', max_length=7),
        ),
    ]
