# Generated by Django 4.1.6 on 2023-08-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0008_alter_account_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="started_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterUniqueTogether(
            name="transaction",
            unique_together={
                ("amount", "currency", "description", "type", "started_at")
            },
        ),
    ]
