# Generated by Django 4.1.6 on 2023-08-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
