# Generated by Django 4.1.6 on 2023-08-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_transaction_additional_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='product',
            field=models.CharField(choices=[('Current', 'Current'), ('Savings', 'Savings'), ('Investments', 'Investments')], default='Current', max_length=11),
        ),
    ]
