# Generated by Django 4.2.4 on 2023-08-31 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0015_alter_transaction_product"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(
                        default="Unidentified",
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
