# Generated by Django 4.2.4 on 2023-08-31 20:48

from django.db import migrations


def create_default_category(apps, _):
    apps.get_model("finance", "Category").objects.create()


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0016_category"),
    ]

    operations = [
        migrations.RunPython(create_default_category),
    ]
