# Generated by Django 4.2.4 on 2023-09-03 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0019_transaction_confirmed_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="category_suggestion",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suggestions",
                to="finance.category",
            ),
        ),
    ]
