# Generated by Django 4.1.6 on 2023-09-22 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0020_transaction_category_suggestion"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("source", models.CharField(max_length=64)),
                ("symbol", models.CharField(max_length=6)),
                ("value", models.DecimalField(decimal_places=4,
                                              max_digits=10)),
            ],
            options={
                "ordering": ("-date", "symbol"),
                "unique_together": {("date", "source", "symbol")},
            },
        ),
    ]
