# Generated by Django 4.1.6 on 2023-12-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0022_delete_exchangerate_alter_credit_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="additional_data",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
