# Generated by Django 4.1.6 on 2024-01-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0025_pnl"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pnl",
            options={"ordering": ["-date_sold", "-date_acquired", "ticker"]},
        ),
        migrations.AlterField(
            model_name="pnl",
            name="date_acquired",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="pnl",
            name="date_sold",
            field=models.DateField(),
        ),
    ]
