# Generated by Django 4.1.6 on 2024-01-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0026_alter_pnl_options_alter_pnl_date_acquired_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pnl",
            name="cost_basis",
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name="pnl",
            name="pnl",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
