# Generated by Django 5.0.4 on 2024-08-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="source",
            options={"ordering": ("name",)},
        ),
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
