# Generated by Django 5.0.4 on 2024-08-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0002_alter_source_options_alter_source_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="source",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="unique_default_source",
            ),
        ),
    ]
