# Generated by Django 5.2.10 on 2026-06-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0003_source_is_default_source_unique_default_source"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="source",
            name="unique_default_source",
        ),
        migrations.RenameField(
            model_name="source",
            old_name="is_default",
            new_name="is_active",
        ),
        migrations.AddField(
            model_name="source",
            name="type",
            field=models.CharField(
                choices=[("local", "Local"), ("regular", "Regular"), ("band", "Band")],
                default="regular",
                max_length=10,
            ),
        ),
    ]
