# Generated by Django 4.1.6 on 2023-10-26 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_remove_debt_to_alter_expensegroup_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debt",
            name="expense",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="debts",
                to="expenses.expense",
            ),
        ),
    ]
