# Generated by Django 5.0.4 on 2024-06-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crons", "0004_cron_args"),
    ]

    operations = [
        migrations.AddField(
            model_name="cron",
            name="kwargs",
            field=models.JSONField(default=dict),
        ),
    ]
