# Generated by Django 5.0.4 on 2024-06-07 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crons", "0005_cron_kwargs"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cron",
            unique_together={("command", "args", "kwargs", "expression")},
        ),
    ]
