# Generated by Django 5.0.4 on 2024-06-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crons", "0006_alter_cron_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="cron",
            name="name",
            field=models.CharField(default="placeholder", max_length=255),
        ),
    ]
