# Generated by Django 5.0.4 on 2025-01-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crons", "0008_alter_cron_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cron",
            unique_together={("command", "kwargs", "expression")},
        ),
        migrations.AddField(
            model_name="cron",
            name="logger_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.RemoveField(
            model_name="cron",
            name="args",
        ),
    ]
