# Generated by Django 5.0.4 on 2025-01-29 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crons", "0009_alter_cron_unique_together_cron_logger_enabled_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cron",
            old_name="logger_enabled",
            new_name="logs_enabled",
        ),
    ]
