# Generated by Django 5.0.4 on 2025-01-29 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crons", "0010_rename_logger_enabled_cron_logs_enabled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cron",
            name="logs_enabled",
        ),
        migrations.AddField(
            model_name="cron",
            name="log_level",
            field=models.IntegerField(default=20),
        ),
    ]
