# Generated by Django 5.0.4 on 2025-01-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crons", "0011_remove_cron_logs_enabled_cron_log_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cron",
            name="log_level",
            field=models.IntegerField(default=30),
        ),
    ]
