# Generated by Django 5.2.10 on 2026-04-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crons", "0012_alter_cron_log_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cron",
            name="log_level",
        ),
    ]
