# Generated by Django 4.1.6 on 2023-02-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Earthquake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("depth", models.FloatField()),
                ("intensity",
                 models.CharField(blank=True, max_length=16, null=True)),
                ("location", models.CharField(max_length=128)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("magnitude", models.FloatField()),
                ("timestamp", models.DateTimeField(unique=True)),
            ],
        ),
    ]
