# Generated by Django 4.1.6 on 2024-01-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("earthquakes", "0004_alter_earthquake_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="earthquake",
            name="depth",
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name="earthquake",
            name="latitude",
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name="earthquake",
            name="longitude",
            field=models.DecimalField(decimal_places=5, max_digits=8),
        ),
        migrations.AlterField(
            model_name="earthquake",
            name="magnitude",
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
