# Generated by Django 4.1.5 on 2023-01-07 12:50

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_data', models.JSONField(blank=True, default=dict, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=32)),
                ('full_name', models.CharField(max_length=32)),
                ('last_called_on', models.DateTimeField(blank=True, null=True)),
                ('last_name', models.CharField(blank=True, max_length=32, null=True)),
                ('telegram_id', models.BigIntegerField()),
                ('token', models.CharField(max_length=64, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=32)),
                ('webhook', models.URLField(blank=True, null=True)),
                ('whitelist', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=24), blank=True, default=list, size=8)),
            ],
        ),
    ]
