# Generated by Django 4.1.5 on 2023-01-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
