# Generated by Django 4.1.6 on 2023-03-29 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('description', models.CharField(default='', max_length=256)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product', models.CharField(choices=[('Current', 'Current'), ('Savings', 'Savings')], max_length=7)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(max_length=24)),
                ('type', models.CharField(choices=[('ATM', 'ATM'), ('CARD_CHARGEBACK', 'Card chargeback'), ('CARD_CREDIT', 'Card credit'), ('CARD_PAYMENT', 'Card payment'), ('CARD_REFUND', 'Card refund'), ('CASHBACK', 'Cashback'), ('EXCHANGE', 'Exchange'), ('FEE', 'Fee'), ('TOPUP', 'Topup'), ('TRANSFER', 'Transfer')], max_length=15)),
            ],
            options={
                'unique_together': {('amount', 'currency', 'description', 'type', 'started_at', 'balance')},
            },
        ),
    ]
