# Generated by Django 4.1.6 on 2023-03-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('description', models.CharField(default='', max_length=256)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product', models.IntegerField(choices=[(1, 'Current'), (2, 'Savings')])),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('state', models.CharField(max_length=24)),
                ('type', models.IntegerField(choices=[(1, 'ATM'), (2, 'CARD_CREDIT'), (3, 'CARD_PAYMENT'), (4, 'CARD_REFUND'), (5, 'EXCHANGE'), (6, 'FEE'), (7, 'TOPUP'), (8, 'TRANSFER')])),
            ],
            options={
                'unique_together': {('amount', 'currency', 'type', 'started_at')},
            },
        ),
    ]
