# Generated by Django 5.1.7 on 2025-08-28 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transit_lines", "0005_alter_schedule_terminal1_schedule_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranzyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("endpoint", models.CharField(max_length=64, unique=True)),
                ("etag", models.CharField(blank=True, max_length=125)),
                ("data", models.JSONField(default=dict)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
