# Generated by Django 5.1.7 on 2025-08-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transit_lines", "0006_tranzyresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="tranzyresponse",
            name="last_checked",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
