# Generated by Django 5.1.7 on 2026-01-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transit_lines", "0007_tranzyresponse_last_checked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transitline",
            name="line_type",
            field=models.CharField(
                choices=[("metropolitan", "Metropolitan"), ("urban", "Urban")],
                max_length=16,
            ),
        ),
    ]
