# Generated by Django 5.0.1 on 2024-03-30 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watchers", "0002_alter_watcher_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="watcher",
            name="cron",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
