# Generated by Django 5.0.1 on 2024-04-01 09:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("watchers", "0004_watcher_top"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watcher",
            name="is_active",
        ),
    ]
