# Generated by Django 5.0.4 on 2024-10-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchers", "0006_watcher_chat_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="watcher",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
