# Generated by Django 5.0.4 on 2025-01-30 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchers", "0007_watcher_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="watcher",
            name="log_level",
            field=models.IntegerField(default=20),
        ),
    ]
