# Generated by Django 5.0.4 on 2025-01-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchers", "0008_watcher_log_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watcher",
            name="log_level",
            field=models.IntegerField(default=30),
        ),
    ]
