# Generated by Django 5.0.4 on 2025-02-19 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchers", "0009_alter_watcher_log_level"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watcher",
            name="top",
        ),
    ]
