# Generated by Django 5.1.7 on 2025-10-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchers", "0010_remove_watcher_top"),
    ]

    operations = [
        migrations.AddField(
            model_name="watcher",
            name="type",
            field=models.IntegerField(choices=[(1, "API"), (2, "Web")], default=2),
        ),
    ]
