# Generated by Django 5.1.7 on 2025-11-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchers", "0011_watcher_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="watcher",
            name="cron_notification",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
