# Generated by Django 5.1.7 on 2025-11-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchers", "0012_watcher_cron_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="watcher",
            name="has_new_data",
            field=models.BooleanField(default=False),
        ),
    ]
