# Generated by Django 6.0.1 on 2026-02-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("watchers", "0013_watcher_has_new_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watcher",
            name="has_new_data",
        ),
        migrations.AddField(
            model_name="watcher",
            name="pending_data",
            field=models.JSONField(default=list),
        ),
    ]
