# Generated by Django 5.2.10 on 2026-04-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("watchers", "0014_remove_watcher_has_new_data_watcher_pending_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="watcher",
            name="log_level",
        ),
    ]
