# Generated by Django 5.0.4 on 2024-04-26 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crons", "0002_alter_cron_unique_together_cron_is_management_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cron",
            name="description",
        ),
        migrations.RemoveField(
            model_name="cron",
            name="is_management",
        ),
    ]
