# Generated by Django 4.1.6 on 2024-01-04 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bots", "0003_rename_is_external_bot_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "additional_data",
                    models.JSONField(blank=True, default=dict, null=True),
                ),
                ("author", models.JSONField()),
                ("chat_id", models.BigIntegerField()),
                ("chat_title", models.CharField(max_length=128)),
                ("date", models.DateTimeField()),
                ("message_id", models.IntegerField()),
                ("saved_by", models.JSONField()),
                ("text", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
