# Generated by Django 5.0.1 on 2024-03-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Watcher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("latest", models.JSONField(default=dict)),
                ("name", models.CharField(max_length=255)),
                ("request", models.JSONField(default=dict)),
                ("selector", models.CharField(max_length=128)),
                ("url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
