# Generated by Django 5.0.1 on 2024-03-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watchers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watcher",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
