# Generated by Django 5.0.1 on 2024-03-31 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watchers", "0003_watcher_cron"),
    ]

    operations = [
        migrations.AddField(
            model_name="watcher",
            name="top",
            field=models.BooleanField(default=True),
        ),
    ]
