# Generated by Django 5.0.1 on 2024-04-02 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watchers", "0005_remove_watcher_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="watcher",
            name="chat_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
