name: build-and-upload
on: [push]
jobs:
  build-and-upload-to-cloud-storage:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v3'
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install
      run: npm install
      working-directory: ./frontend
    - name: build frontend
      run: npm run build --if-present
      working-directory: ./frontend
    - id: 'upload-folder'
      uses: 'google-github-actions/upload-cloud-storage@v1'
      with:
        working-directory: ./frontend
        path: './build'
        destination: ${{ secrets.BUCKET_NAME }}
