name: telegram message
on:
  workflow_run:
    workflows:
      - CI/CD
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion }}
    steps:
      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          disable_notification: true
          disable_web_page_preview: true
          format: html
          message: |
            <a target='_blank' href='${{ github.event.workflow_run.html_url }}'>${{ github.event.workflow_run.name }} - ${{ github.event.action }}</a>
            ${{ github.event.workflow_run.conclusion }}
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}

